import math
import turtle

def familyname():
    turtle.up()
    turtle.left(180)
    turtle.forward(200)
    turtle.left(180)
    turtle.down()

    # A
    A()
    # R
    R()
    # U
    U()
    # P
    P()
    # A
    A()
    # R
    R()
    # A
    A()

    turtle.mainloop()

def A():
    turtle.up()
    turtle.forward(40)
    turtle.down()
    turtle.left(90)
    turtle.forward(60)
    turtle.left(45)
    turtle.forward(10 * math.sqrt(2))
    turtle.left(45)
    turtle.forward(20)
    turtle.left(45)
    turtle.forward(10 * math.sqrt(2))
    turtle.left(45)
    turtle.forward(60)
    turtle.left(180)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(40)
    turtle.right(180)
    turtle.forward(40)
    turtle.left(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.up()
    turtle.forward(50)
    turtle.down()

def R():
    turtle.left(90)
    turtle.forward(70)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(45)
    turtle.forward(10*math.sqrt(2))
    turtle.right(45)
    turtle.forward(20)
    turtle.right(45)
    turtle.forward(10*math.sqrt(2))
    turtle.right(45)
    turtle.forward(30)
    turtle.right(180)
    turtle.forward(30)
    turtle.right(45)
    turtle.forward(10*math.sqrt(2))
    turtle.right(45)
    turtle.forward(20)
    turtle.up()
    turtle.right(90)
    turtle.forward(40)
    turtle.right(180)
    turtle.forward(50)
    turtle.down()

def U():
    turtle.up()
    turtle.left(90)
    turtle.forward(10)
    turtle.down()

    turtle.forward(60)
    turtle.left(180)
    turtle.forward(60)
    turtle.left(45)
    turtle.forward(10 * math.sqrt(2))
    turtle.left(45)
    turtle.forward(20)
    turtle.left(45)
    turtle.forward(10 * math.sqrt(2))
    turtle.left(45)
    turtle.forward(60)

    turtle.right(180)
    turtle.forward(60)
    turtle.right(45)
    turtle.forward(10 * math.sqrt(2))
    turtle.right(45)
    turtle.forward(20)
    turtle.up()
    turtle.forward(10)
    turtle.right(180)
    turtle.forward(50)
    turtle.down()

def P():
    turtle.left(90)
    turtle.forward(70)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(45)
    turtle.forward(10 * math.sqrt(2))
    turtle.right(45)
    turtle.forward(20)
    turtle.right(45)
    turtle.forward(10 * math.sqrt(2))
    turtle.right(45)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.up()
    turtle.forward(50)
    turtle.down()

familyname()